schema: prism.release-studio.configuration/1
title: USB-PD Trigger Board production release
board: USB-PD-Trigger-Board.kicad_pcb
schematic: USB-PD-Trigger-Board.kicad_sch
jobset: Outputs.kicad_jobset
default_variant: default
fields:
  via_treatment: Tented
  assembly_ipc_class: '2'
  solder_mask_colour: Green
  manufacturing_ipc_class: '2'
notes: {}
variants:
- default
typography: geist-pixel-square
document_number: USB-PD-TRIG
revision: A
vendors: []
